name: Runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: bash run.sh

      - uses: romdotdog/git-auto-commit-action@master
        with:
          commit_message: build
